---
- import_tasks: timezone.yml
- import_tasks: selinux.yml
- import_tasks: firewalld.yml
- import_tasks: hostname.yml
- import_tasks: hosts.yml
- import_tasks: login.yml
#- import_tasks: proxy.yml
#- import_tasks: yum.yml
