---
- name: add kube group
  group:
    name: kube
    state: present
    system: yes
            
- name: add kube user
  user:
    name: kube
    shell: /sbin/nologin
    groups: kube
    append: yes
    system: yes

- name: fetch kube-apiserver binary to PATH(/usr/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kube-apiserver"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  notify: change ssl-folod permision  


- name: create kube-apiserver configuration
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'config.j2', dest: '/etc/kubernetes/config' }
    - { src: 'apiserver.j2', dest: '/etc/kubernetes/apiserver' }
    - { src: 'kube-apiserver.service', dest: '/lib/systemd/system/kube-apiserver.service' }
  notify: restart kube-apiserver

- name: systemd daemon-reload
  systemd: 
    daemon-reload: yes

- name: start kubernetes-master
  service: 
    name: kube-apiserver
    state: started 
    enabled: yes
