---
- name: fetch kubelet binary to PATH(/usr/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kubelet"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755

- name: create kubernetes-node directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/kubernetes
    - /var/lib/kubelet

- name: create kubernetes-node configuration
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'config.j2', dest: '/etc/kubernetes/config' }
    - { src: 'kubelet_{{ kubernetes_version }}.j2', dest: '/etc/kubernetes/kubelet' }
    - { src: 'kubelet.service', dest: '/lib/systemd/system/kubelet.service' }
  notify: restart kubelet
   
- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start kubelet
  service: 
    name: kubelet
    state: started 
    enabled: yes
