---
- name: apply k8s-ingress
  shell: kubectl apply -f /var/tmp/k8s-ingress/{{ item }}
  with_items:
    - namespace.yaml
    - default-backend.yaml
    - configmap.yaml
    - tcp-services-configmap.yaml
    - udp-services-configmap.yaml
    - rbac.yaml
    - with-rbac.yaml
